stages:
  - test
  - deploy

test_job:
  type: test
  script:
    - echo "hello github ci"
    - ls

deploy_job:
  type: deploy
  script:
    - echo "hello github ci" > helo.txt
    - ls > ls.txt
  artifacts:
    paths:
      - helo.txt
      - ls.txt
